[package]
name = "dcv-color-primitives"
version = "0.1.0"
edition = "2018"
description = "a library to perform image color model conversion"
license = "MIT-0"
repository = "https://github.com/aws/dcv-color-primitives"
authors = ["Fabio Lagalla <lagfabio@amazon.com>"]
readme = "README.md"
keywords = ["colors", "converter", "rgb", "yuv"]
categories = ["graphics", "video"]

[lib]
name = "dcv_color_primitives"
crate-type = ["staticlib", "rlib"]

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "benches"
harness = false