[package]
name = "dcv-color-primitives"
version = "0.1.0"
authors = ["Fabio Lagalla <lagfabio@amazon.com>"]
edition = "2018"

[lib]
name = "dcv_color_primitives"
crate-type = ["staticlib", "rlib"]

[dev-dependencies]
criterion = "0.3.0"

[[bench]]
name = "benches"
harness = false